const emojiMap = {
    dog: ['🐶', '🐕', '🐩'],
    cat: ['🐱', '🐈'],
    pizza: ['🍕'],
    book: ['📚', '📖', '📕', '📗', '📘', '📙'],
    car: ['🚗', '🚙', '🏎️', '🚓', '🚑', '🚒', '🚐', '🚚', '🚛', '🚜'],
    computer: ['💻', '🖥️', '⌨️'],
    code: ['💻', '📜', '👨‍💻', '👩‍💻'],
    javascript: ['📜', '💛'],
    python: ['🐍'],
    react: ['⚛️'],
    angular: ['🅰️'],
    vue: ['🖖'],
    node: ['🟩'],
    server: ['🖥️', '🗄️'],
    database: ['🗄️', '💾'],
    cloud: ['☁️'],
    weather: ['🌦️', '☀️', '🌧️', '❄️', '🌪️'],
    sun: ['☀️', '🌞'],
    moon: ['🌙', '🌕', '🌑'],
    star: ['⭐', '🌟', '✨'],
    flower: ['🌸', '🌹', '🌷', '🌻', '🌼'],
    tree: ['🌳', '🌲', '🌴'],
    food: ['🍔', '🍕', '🍟', '🍎', '🥦', '🍣'],
    fruit: ['🍎', '🍌', '🍇', '🍓', '🍉'],
    vegetable: ['🥦', '🥕', '🌽', '🍆', '🍅'],
    money: ['💰', '💵', '💴', '💶', '💷', '🪙'],
    love: ['❤️', '💖', '💕', '😍', '😘'],
    heart: ['❤️', '💔', '💖', '💕', '💓', '💜', '💙', '💚', '💛'],
    music: ['🎵', '🎶', '🎸', '🎹', '🎺', '🎻', '🥁'],
    movie: ['🎬', '🎥', '🎞️', '📽️'],
    game: ['🎮', '🎲', '♟️', '🕹️'],
    sport: ['⚽', '🏀', '🏈', '⚾', '🎾'],
    ball: ['🏀', '⚽', '🏈', '⚾', '🎾', '🏐'],
    travel: ['✈️', '🚀', '🚂', '🚢', '🌍'],
    world: ['🌍', '🌎', '🌏'],
    usa: ['🇺🇸', '🦅'],
    india: ['🇮🇳', '🦚'],
    uk: ['🇬🇧'],
    canada: ['🇨🇦'],
    australia: ['🇦🇺', '🐨', '🦘'],
    japan: ['🇯🇵', '🌸', '🍣'],
    china: ['🇨🇳', '🐼', '🐉'],
    germany: ['🇩🇪', '🍺'],
    france: ['🇫🇷', '🍷', '🥐'],
    brazil: ['🇧🇷', '⚽'],
    russia: ['🇷🇺'],
    mexico: ['🇲🇽', '🌮'],
    spain: ['🇪🇸', '💃'],
    italy: ['🇮🇹', '🍕', '🍝'],
    korea: ['🇰🇷'],
    coffee: ['☕'],
    tea: ['🍵'],
    beer: ['🍺', '🍻'],
    wine: ['🍷', '🍇'],
    cocktail: ['🍸', '🍹'],
    party: ['🎉', '🎊', '🎈'],
    birthday: ['🎂', '🎁'],
    christmas: ['🎄', '🎅', '🎁'],
    halloween: ['🎃', '👻', '💀'],
    newyear: ['🎆', '🎇'],
    congratulations: ['🎊', '🎉'],
    thankyou: ['🙏'],
    sorry: ['😥', '😔'],
    help: ['🆘', '🙋'],
    idea: ['💡'],
    question: ['❓', '❔'],
    warning: ['⚠️'],
    error: ['❌', '❗'],
    success: ['✅', '👍'],
    check: ['✔️', '☑️'],
    github: ['🐙', '👨‍💻', '👩‍💻'],
    twitter: ['🐦'],
    facebook: ['👍', '💙'],
    instagram: ['📸'],
    linkedin: ['💼'],
    youtube: ['📺', '▶️'],
    slack: ['💬'],
    discord: ['🎮'],
    skype: ['📞'],
    whatsapp: ['📱'],
    email: ['📧', '✉️'],
    phone: ['☎️', '📞', '📱'],
    home: ['🏠', '🏡'],
    house: ['🏡', '🏠'],
    office: ['🏢', '💼'],
    school: ['🏫', '🎓'],
    hospital: ['🏥', '⚕️'],
    bank: ['🏦', '💰'],
    hotel: ['🏨'],
    shop: ['🏬', '🛍️'],
    store: ['🏪', '🛒'],
    market: ['🛒', '📈', '📉'],
    restaurant: ['🍴', '🍝', '🍜'],
    cafe: ['☕', '🥐'],
    bar: ['🍻', '🍸'],
    park: ['🏞️', '🌳'],
    beach: ['🏖️', '🌊', '☀️'],
    mountain: ['⛰️', '🏔️'],
    forest: ['🌲', '🌳'],
    city: ['🏙️', '🌇', '🌃'],
    town: ['🏘️'],
    village: ['🏡'],
    bridge: ['🌉'],
    road: ['🛣️', '🚗'],
    train: ['🚆', '🚂', '🚄'],
    bus: ['🚌'],
    taxi: ['🚕', '🚖'],
    bicycle: ['🚲', '🚴'],
    motorcycle: ['🏍️'],
    ship: ['🚢', '🛳️', '⛴️'],
    boat: ['⛵', '🚤'],
    rocket: ['🚀'],
    fire: ['🔥', '🚒'],
    water: ['💧', '🌊', '💦'],
    earth: ['🌎', '🌍', '🌏'],
    air: ['💨', '🌬️'],
    science: ['🔬', '⚗️', '🧬'],
    art: ['🎨', '🖼️'],
    history: ['📜', '🏛️'],
    math: ['🔢', '➕', '➖', '✖️', '➗'],
    musicnote: ['🎶', '🎵'],
    headphone: ['🎧'],
    microphone: ['🎤'],
    camera: ['📷', '📸'],
    video: ['📹', '🎥'],
    tv: ['📺'],
    laptop: ['💻'],
    phonecall: ['📞'],
    watch: ['⌚'],
    clock: ['⏰', '🕰️'],
    calendar: ['📅', '📆'],
    news: ['📰', '🗞️'],
    document: ['📄', '📃', '📑'],
    folder: ['📁', '📂'],
    file: ['📂', '📄'],
    chart: ['📈', '📉', '📊'],
    graph: ['📊', '📈', '📉'],
    pin: ['📌', '📍'],
    link: ['🔗'],
    key: ['🔑', '🗝️'],
    lock: ['🔒', '🔐'],
    unlock: ['🔓'],
    search: ['🔍', '🔎'],
    zoom: ['🔎', '🔍'],
    light: ['💡', '🕯️'],
    dark: ['🌑', '⚫'],
    happy: ['😄', '😊', '😃', '😁'],
    sad: ['😢', '😭', '😔', '😞'],
    angry: ['😠', '😡', '😤'],
    laugh: ['😂', '🤣'],
    cry: ['😭', '😢'],
    smile: ['😊', '🙂', '😄'],
    wink: ['😉'],
    kiss: ['😘', '💋'],
    hug: ['🤗'],
    think: ['🤔', '🧐'],
    sleep: ['😴', '😪'],
    wave: ['👋', '🌊'],
    clap: ['👏'],
    fist: ['✊'],
    peace: ['✌️'],
    rock: ['🤘', '🗿'],
    muscle: ['💪'],
    brain: ['🧠'],
    ghost: ['👻'],
    alien: ['👽', '👾'],
    robot: ['🤖'],
    poop: ['💩'],
    hundred: ['💯'],
    boom: ['💥', '💣'],
    sweat: ['💦', '💧'],
    dash: ['💨'],
    hole: ['🕳️'],
    bomb: ['💣', '💥'],
    knife: ['🔪', '🗡️'],
    gun: ['🔫'],
    pill: ['💊'],
    syringe: ['💉'],
    drop: ['💧'],
    fireworks: ['🎆', '🎇'],
    sparkles: ['✨', '💖'],
    star2: ['🌟'],
    dizzy: ['💫', '😵'],
    comet: ['☄️'],
    rainbow: ['🌈'],
    umbrella: ['☔', '☂️'],
    zap: ['⚡', '🌩️'],
    snowflake: ['❄️'],
    snowman: ['⛄', '☃️'],
    cyclone: ['🌀'],
    foggy: ['🌁'],
    ocean: ['🌊', '💧'],
    cat2: ['🐈', '🐱'],
    dog2: ['🐕', '🐶'],
    mouse: ['🐁', '🐭'],
    hamster: ['🐹'],
    rabbit: ['🐇', '🐰'],
    fox: ['🦊'],
    bear: ['🐻', '🧸'],
    panda: ['🐼'],
    koala: ['🐨'],
    tiger: ['🐅', '🐯'],
    lion: ['🦁'],
    cow: ['🐄', '🐮'],
    pig: ['🐖', '🐷'],
    frog: ['🐸'],
    octopus: ['🐙'],
    shell: ['🐚'],
    bug: ['🐛', '🐞', '🐜', '🕷️'],
    ant: ['🐜'],
    bee: ['🐝', '🍯'],
    ladybug: ['🐞'],
    spider: ['🕷️', '🕸️'],
    scorpion: ['🦂'],
    crab: ['🦀'],
    snake: ['🐍'],
    lizard: ['🦎'],
    turtle: ['🐢'],
    fish: ['🐠', '🐟', '🎣'],
    dolphin: ['🐬'],
    whale: ['🐋', '🐳'],
    shark: ['🦈'],
    bird: ['🐦', '🕊️', '🦅', '🦆', '🦉'],
    eagle: ['🦅'],
    duck: ['🦆'],
    owl: ['🦉'],
    bat: ['🦇'],
    wolf: ['🐺'],
    boar: ['🐗'],
    horse: ['🐴', '🐎'],
    unicorn: ['🦄'],
    zebra: ['🦓'],
    deer: ['🦌'],
    gorilla: ['🦍'],
    monkey: ['🐒', '🐵'],
    rooster: ['🐓'],
    chicken: ['🐔', '🍗'],
    penguin: ['🐧'],
    dodo: ['🦤'],
    sloth: ['🦥'],
    otter: ['🦦'],
    skunk: ['🦨'],
    kangaroo: ['🦘'],
    badger: ['🦡'],
    elephant: ['🐘'],
    rhino: ['🦏'],
    hippo: ['🦛'],
    camel: ['🐫', '🐪'],
    giraffe: ['🦒'],
    crocodile: ['🐊'],
    dragon: ['🐉', '🐲'],
    sauropod: ['🦕'],
    trex: ['🦖'],
    ram: ['🐏'],
    goat: ['🐐'],
    sheep: ['🐑'],
    poodle: ['🐩'],
    turkey: ['🦃'],
    dove: ['🕊️'],
    rat: ['🐀'],
    chipmunk: ['🐿️'],
    hedgehog: ['🦔'],
    face: ['🙂', '😊', '😀', '😔', '😡'],
    person: ['🧑', '👨', '👩'],
    man: ['👨', '👱‍♂️', '🧔'],
    woman: ['👩', '�‍♀️', '�👩‍🦰'],
    boy: ['👦'],
    girl: ['👧'],
    baby: ['👶'],
    oldman: ['👴'],
    oldwoman: ['👵'],
    police: ['👮', '🚓'],
    doctor: ['👨‍⚕️', '👩‍⚕️', '🩺'],
    nurse: ['👩‍⚕️', '👨‍⚕️'],
    student: ['👨‍🎓', '👩‍🎓', '🎓'],
    teacher: ['👩‍🏫', '👨‍🏫'],
    judge: ['👨‍⚖️', '👩‍⚖️', '⚖️'],
    farmer: ['👨‍🌾', '👩‍🌾', '🚜'],
    cook: ['👨‍🍳', '👩‍🍳', '🍳'],
    mechanic: ['👨‍🔧', '👩‍🔧', '🔧'],
    factory: ['🏭'],
    artist: ['👨‍🎨', '👩‍🎨', '🎨'],
    pilot: ['👨‍✈️', '👩‍✈️', '✈️'],
    astronaut: ['👨‍🚀', '👩‍🚀', '🚀'],
    firefighter: ['👨‍🚒', '👩‍🚒', '🚒'],
    prince: ['🤴'],
    princess: ['👸'],
    superhero: ['🦸', '🦸‍♂️', '🦸‍♀️'],
    villain: ['🦹', '🦹‍♂️', '🦹‍♀️'],
    ninja: ['🥷'],
    zombie: ['🧟', '🧟‍♂️', '🧟‍♀️'],
    elf: ['🧝', '🧝‍♂️', '🧝‍♀️'],
    genie: ['🧞', '🧞‍♂️', '🧞‍♀️'],
    vampire: ['🧛', '🧛‍♂️', '🧛‍♀️'],
    mermaid: ['🧜', '🧜‍♂️', '🧜‍♀️'],
    fairy: ['🧚', '🧚‍♂️', '🧚‍♀️'],
    angel: ['👼'],
    santa: ['🎅'],
    mrsclaus: ['🤶'],
    dancer: ['💃', '🕺'],
    runner: ['🏃', '🏃‍♀️', '🏃‍♂️'],
    swimmer: ['🏊', '🏊‍♀️', '🏊‍♂️'],
    surfer: ['🏄', '🏄‍♀️', '🏄‍♂️'],
    skier: ['⛷️'],
    snowboarder: ['🏂'],
    golfer: ['🏌️', '🏌️‍♀️', '🏌️‍♂️'],
    biker: ['🚴', '🚴‍♀️', '🚴‍♂️'],
    weightlifter: ['🏋️', '🏋️‍♀️', '🏋️‍♂️'],
    boxer: ['🥊'],
    martialarts: ['🥋'],
    wrestler: ['🤼', '🤼‍♀️', '🤼‍♂️'],
    gymnast: ['🤸', '🤸‍♀️', '🤸‍♂️'],
    juggler: ['🤹', '🤹‍♀️', '🤹‍♂️'],
    magician: ['🧙', '🧙‍♀️', '🧙‍♂️'],
    clown: ['🤡'],
    mummy: ['🧟'],
    troll: ['🧌'],
    ogre: ['👹'],
    goblin: ['👺'],
    skeleton: ['💀'],
    skull: ['☠️', '💀'],
    jackolantern: ['🎃'],
    gift: ['🎁'],
    balloon: ['🎈'],
    confetti: ['🎊'],
    tada: ['🎉'],
    trophy: ['🏆'],
    medal: ['🏅', '🥇', '🥈', '🥉'],
    prize: ['🥇'],
    soccer: ['⚽'],
    baseball: ['⚾'],
    basketball: ['🏀'],
    volleyball: ['🏐'],
    football: ['🏈'],
    rugby: ['🏉'],
    tennis: ['🎾', 'ρακέτα'],
    bowling: ['🎳'],
    cricket: ['🏏'],
    fieldhockey: ['🏑'],
    icehockey: ['🏒'],
    lacrosse: ['🥍'],
    pingpong: ['🏓'],
    badminton: ['🏸'],
    boxing: ['🥊'],
    ice_skate: ['⛸️'],
    fishing: ['🎣'],
    running: ['🏃‍♀️', '🏃', '🏃‍♂️'],
    ski: ['🎿'],
    sled: ['🛷'],
    curling: ['🥌'],
    dart: ['🎯'],
    yo_yo: ['🪀'],
    kite: ['🪁'],
    '8ball': ['🎱'],
    crystal_ball: ['🔮'],
    nazar_amulet: ['🧿'],
    joystick: ['🕹️'],
    slot_machine: ['🎰'],
    die: ['🎲'],
    puzzle: ['🧩'],
    chess: ['♟️'],
    mahjong: ['🀄'],
    flower_playing_cards: ['🎴'],
    performing_arts: ['🎭'],
    frame_with_picture: ['🖼️'],
    artist_palette: ['🎨'],
    thread: ['🧵'],
    yarn: ['🧶'],
    glove: ['🧤'],
    scarf: ['🧣'],
    coat: ['🧥', '👚'],
    socks: ['🧦'],
    dress: ['👗'],
    kimono: ['👘'],
    sari: ['🥻'],
    one_piece_swimsuit: ['🩱'],
    briefs: ['🩲'],
    shorts: ['🩳'],
    bikini: ['👙'],
    womans_clothes: ['👚'],
    purse: ['👛'],
    handbag: ['👜'],
    clutch_bag: ['👝'],
    shopping_bags: ['🛍️'],
    school_satchel: ['🎒'],
    thong_sandal: ['🩴'],
    mans_shoe: ['👞'],
    athletic_shoe: ['👟'],
    hiking_boot: ['🥾'],
    flat_shoe: ['🥿'],
    high_heeled_shoe: ['👠'],
    womans_sandal: ['👡'],
    ballet_shoes: ['🩰'],
    womans_boot: ['👢'],
    crown: ['👑'],
    womans_hat: ['👒'],
    top_hat: ['🎩'],
    graduation_cap: ['🎓'],
    billed_cap: ['🧢'],
    military_helmet: ['🪖'],
    rescue_workers_helmet: ['⛑️'],
    prayer_beads: ['📿'],
    lipstick: ['💄'],
    ring: ['💍'],
    gem_stone: ['💎'],
    muted_speaker: ['🔇'],
    speaker_low_volume: ['🔈'],
    speaker_medium_volume: ['🔉'],
    speaker_high_volume: ['🔊'],
    loudspeaker: ['📢'],
    megaphone: ['📣'],
    postal_horn: ['📯'],
    bell: ['🔔'],
    no_bell: ['🔕'],
    musical_score: ['🎼'],
    musical_note: ['🎵'],
    musical_notes: ['🎶'],
    studio_microphone: ['🎙️'],
    level_slider: ['🎚️'],
    control_knobs: ['🎛️'],
    headphones: ['🎧'],
    radio: ['📻'],
    saxophone: ['🎷'],
    accordion: ['🪗'],
    guitar: ['🎸'],
    musical_keyboard: ['🎹'],
    trumpet: ['🎺'],
    violin: ['🎻'],
    banjo: ['🪕'],
    drum: ['🥁'],
    long_drum: ['🪘'],
    mobile_phone: ['📱'],
    mobile_phone_with_arrow: ['📲'],
    telephone: ['☎️'],
    telephone_receiver: ['📞'],
    pager: ['📟'],
    fax_machine: ['📠'],
    battery: ['🔋'],
    electric_plug: ['🔌'],
    desktop_computer: ['🖥️'],
    printer: ['🖨️'],
    keyboard: ['⌨️'],
    computer_mouse: ['🖱️'],
    trackball: ['🖲️'],
    computer_disk: ['💽'],
    floppy_disk: ['💾'],
    optical_disk: ['💿'],
    dvd: ['📀'],
    abacus: ['🧮'],
    movie_camera: ['🎥'],
    film_frames: ['🎞️'],
    film_projector: ['📽️'],
    clapper_board: ['🎬'],
    television: ['📺'],
    camera_with_flash: ['📸'],
    video_camera: ['📹'],
    videocassette: ['📼'],
    magnifying_glass_tilted_left: ['🔍'],
    magnifying_glass_tilted_right: ['🔎'],
    candle: ['🕯️'],
    light_bulb: ['💡'],
    flashlight: ['🔦'],
    red_paper_lantern: ['🏮'],
    diya_lamp: ['🪔'],
    notebook_with_decorative_cover: ['📔'],
    closed_book: ['📕'],
    open_book: ['📖'],
    green_book: ['📗'],
    blue_book: ['📘'],
    orange_book: ['📙'],
    books: ['📚'],
    notebook: ['📓'],
    ledger: ['📒'],
    page_with_curl: ['📃'],
    scroll: ['📜'],
    page_facing_up: ['📄'],
    newspaper: ['📰'],
    rolled_up_newspaper: ['🗞️'],
    bookmark_tabs: ['📑'],
    bookmark: ['🔖'],
    label: ['🏷️'],
    money_bag: ['💰'],
    coin: ['🪙'],
    yen_banknote: ['💴'],
    dollar_banknote: ['💵'],
    euro_banknote: ['💶'],
    pound_banknote: ['💷'],
    money_with_wings: ['💸'],
    credit_card: ['💳'],
    receipt: ['🧾'],
    chart_increasing_with_yen: ['💹'],
    envelope: ['✉️'],
    e_mail: ['📧'],
    incoming_envelope: ['📨'],
    envelope_with_arrow: ['📩'],
    outbox_tray: ['📤'],
    inbox_tray: ['📥'],
    package: ['📦'],
    closed_mailbox_with_raised_flag: ['📫'],
    closed_mailbox_with_lowered_flag: ['📪'],
    open_mailbox_with_raised_flag: ['📬'],
    open_mailbox_with_lowered_flag: ['📭'],
    postbox: ['📮'],
    ballot_box_with_ballot: ['🗳️'],
    pencil: ['✏️'],
    black_nib: ['✒️'],
    fountain_pen: ['🖋️'],
    pen: ['🖊️'],
    paintbrush: ['🖌️'],
    crayon: ['🖍️'],
    memo: ['📝'],
    briefcase: ['💼'],
    file_folder: ['📁'],
    open_file_folder: ['📂'],
    card_index_dividers: ['🗂️'],
    tear_off_calendar: ['📆'],
    spiral_notepad: ['🗒️'],
    spiral_calendar: ['🗓️'],
    card_index: ['📇'],
    chart_increasing: ['📈'],
    chart_decreasing: ['📉'],
    bar_chart: ['📊'],
    clipboard: ['📋'],
    pushpin: ['📌'],
    round_pushpin: ['📍'],
    paperclip: ['📎'],
    linked_paperclips: ['🖇️'],
    straight_ruler: ['📏'],
    triangular_ruler: ['📐'],
    scissors: ['✂️'],
    card_file_box: ['🗃️'],
    file_cabinet: ['🗄️'],
    wastebasket: ['🗑️'],
    locked: ['🔒'],
    unlocked: ['🔓'],
    locked_with_pen: ['🔏'],
    locked_with_key: ['🔐'],
    old_key: ['🗝️'],
    hammer: ['🔨'],
    axe: ['🪓'],
    pick: ['⛏️'],
    hammer_and_pick: ['⚒️'],
    hammer_and_wrench: ['🛠️'],
    dagger: ['🗡️'],
    crossed_swords: ['⚔️'],
    pistol: ['🔫'],
    bow_and_arrow: ['🏹'],
    shield: ['🛡️'],
    wrench: ['🔧'],
    nut_and_bolt: ['🔩'],
    gear: ['⚙️'],
    clamp: ['🗜️'],
    balance_scale: ['⚖️'],
    white_cane: ['🦯'],
    chains: ['⛓️'],
    toolbox: ['🧰'],
    magnet: ['🧲'],
    alembic: ['⚗️'],
    test_tube: ['🧪'],
    petri_dish: ['🧫'],
    dna: ['🧬'],
    microscope: ['🔬'],
    telescope: ['🔭'],
    satellite_antenna: ['📡'],
    stethoscope: ['🩺'],
    door: ['🚪'],
    elevator: ['🛗'],
    mirror: ['🪞'],
    window: ['🪟'],
    bed: ['🛏️'],
    couch_and_lamp: ['🛋️'],
    chair: ['🪑'],
    toilet: ['🚽'],
    plunger: ['🪠'],
    shower: ['🚿'],
    bathtub: ['🛁'],
    mouse_trap: ['🪤'],
    razor: ['🪒'],
    lotion_bottle: ['🧴'],
    safety_pin: ['🧷'],
    broom: ['🧹'],
    basket: ['🧺'],
    roll_of_paper: ['🧻'],
    bucket: ['🪣'],
    soap: ['🧼'],
    toothbrush: ['🪥'],
    sponge: ['🧽'],
    fire_extinguisher: ['🧯'],
    shopping_cart: ['🛒'],
    cigarette: ['🚬'],
    coffin: ['⚰️'],
    headstone: ['🪦'],
    funeral_urn: ['⚱️'],
    moai: ['🗿'],
    placard: ['🪧'],
    atm_sign: ['🏧'],
    litter_in_bin_sign: ['🚮'],
    potable_water: ['🚰'],
    wheelchair_symbol: ['♿'],
    mens_room: ['🚹'],
    womens_room: ['🚺'],
    restroom: ['🚻'],
    baby_symbol: ['🚼'],
    water_closet: ['🚾'],
    passport_control: ['🛂'],
    customs: ['🛃'],
    baggage_claim: ['🛄'],
    left_luggage: ['🛅'],
    children_crossing: ['🚸'],
    no_entry: ['⛔'],
    prohibited: ['🚫'],
    no_bicycles: ['🚳'],
    no_smoking: ['🚭'],
    no_littering: ['🚯'],
    non_potable_water: ['🚱'],
    no_pedestrians: ['🚷'],
    no_mobile_phones: ['📵'],
    no_one_under_eighteen: ['🔞'],
    radioactive: ['☢️'],
    biohazard: ['☣️'],
    up_arrow: ['⬆️'],
    up_right_arrow: ['↗️'],
    right_arrow: ['➡️'],
    down_right_arrow: ['↘️'],
    down_arrow: ['⬇️'],
    down_left_arrow: ['↙️'],
    left_arrow: ['⬅️'],
    up_left_arrow: ['↖️'],
    up_down_arrow: ['↕️'],
    left_right_arrow: ['↔️'],
    right_arrow_curving_left: ['↩️'],
    left_arrow_curving_right: ['↪️'],
    right_arrow_curving_up: ['⤴️'],
    right_arrow_curving_down: ['⤵️'],
    clockwise_vertical_arrows: ['🔃'],
    counterclockwise_arrows_button: ['🔄'],
    back_arrow: ['🔙'],
    end_arrow: ['🔚'],
    on_arrow: ['🔛'],
    soon_arrow: ['🔜'],
    top_arrow: ['🔝'],
    place_of_worship: ['🛐'],
    atom_symbol: ['⚛️'],
    om: ['🕉️'],
    star_of_david: ['✡️'],
    wheel_of_dharma: ['☸️'],
    yin_yang: ['☯️'],
    latin_cross: ['✝️'],
    orthodox_cross: ['☦️'],
    star_and_crescent: ['☪️'],
    peace_symbol: ['☮️'],
    menorah: ['🕎'],
    dotted_six_pointed_star: ['🔯'],
    aries: ['♈'],
    taurus: ['♉'],
    gemini: ['♊'],
    cancer: ['♋'],
    leo: ['♌'],
    virgo: ['♍'],
    libra: ['♎'],
    scorpio: ['♏'],
    sagittarius: ['♐'],
    capricorn: ['♑'],
    aquarius: ['♒'],
    pisces: ['♓'],
    ophiuchus: ['⛎'],
    shuffle_tracks_button: ['🔀'],
    repeat_button: ['🔁'],
    repeat_single_button: ['🔂'],
    play_button: ['▶️'],
    fast_forward_button: ['⏩'],
    next_track_button: ['⏭️'],
    play_or_pause_button: ['⏯️'],
    reverse_button: ['◀️'],
    fast_reverse_button: ['⏪'],
    last_track_button: ['⏮️'],
    upwards_button: ['🔼'],
    fast_up_button: ['⏫'],
    downwards_button: ['🔽'],
    fast_down_button: ['⏬'],
    pause_button: ['⏸️'],
    stop_button: ['⏹️'],
    record_button: ['⏺️'],
    eject_button: ['⏏️'],
    cinema: ['🎦'],
    dim_button: ['🔅'],
    bright_button: ['🔆'],
    antenna_bars: ['📶'],
    vibration_mode: ['📳'],
    mobile_phone_off: ['📴'],
    female_sign: ['♀️'],
    male_sign: ['♂️'],
    transgender_symbol: ['⚧️'],
    multiply: ['✖️'],
    plus: ['➕'],
    minus: ['➖'],
    divide: ['➗'],
    infinity: ['♾️'],
    double_exclamation_mark: ['‼️'],
    exclamation_question_mark: ['⁉️'],
    red_question_mark: ['❓'],
    white_question_mark: ['❔'],
    white_exclamation_mark: ['❕'],
    red_exclamation_mark: ['❗'],
    wavy_dash: ['〰️'],
    currency_exchange: ['💱'],
    heavy_dollar_sign: ['💲'],
    medical: ['⚕️'],
    recycling_symbol: ['♻️'],
    fleur_de_lis: ['⚜️'],
    trident_emblem: ['🔱'],
    name_badge: ['📛'],
    japanese_symbol_for_beginner: ['🔰'],
    hollow_red_circle: ['⭕'],
    check_mark_button: ['✅'],
    check_box_with_check: ['☑️'],
    check_mark: ['✔️'],
    cross_mark: ['❌'],
    cross_mark_button: ['❎'],
    curly_loop: ['➰'],
    double_curly_loop: ['➿'],
    part_alternation_mark: ['〽️'],
    eight_spoked_asterisk: ['✳️'],
    eight_pointed_star: ['✴️'],
    sparkle: ['❇️'],
    copyright: ['©️'],
    registered: ['®️'],
    trade_mark: ['™️'],
    keycap_hash: ['#️⃣'],
    keycap_asterisk: ['*️⃣'],
    keycap_0: ['0️⃣'],
    keycap_1: ['1️⃣'],
    keycap_2: ['2️⃣'],
    keycap_3: ['3️⃣'],
    keycap_4: ['4️⃣'],
    keycap_5: ['5️⃣'],
    keycap_6: ['6️⃣'],
    keycap_7: ['7️⃣'],
    keycap_8: ['8️⃣'],
    keycap_9: ['9️⃣'],
    keycap_10: ['🔟'],
    input_latin_uppercase: ['🔠'],
    input_latin_lowercase: ['🔡'],
    input_numbers: ['🔢'],
    input_symbols: ['🔣'],
    input_latin_letters: ['🔤'],
    a_button_blood_type: ['🅰️'],
    ab_button_blood_type: ['🆎'],
    b_button_blood_type: ['🅱️'],
    cl_button: ['🆑'],
    cool_button: ['🆒'],
    free_button: ['🆓'],
    information: ['ℹ️'],
    id_button: ['🆔'],
    circled_m: ['Ⓜ️'],
    new_button: ['🆕'],
    ng_button: ['🆖'],
    o_button_blood_type: ['🅾️'],
    ok_button: ['🆗'],
    p_button: ['🅿️'],
    sos_button: ['🆘'],
    up_button: ['🆙'],
    vs_button: ['🆚'],
    japanese_here_button: ['🈁'],
    japanese_service_charge_button: ['🈂️'],
    japanese_monthly_amount_button: ['🈷️'],
    japanese_not_free_of_charge_button: ['🈶'],
    japanese_reserved_button: ['🈯'],
    japanese_bargain_button: ['🉐'],
    japanese_discount_button: ['🈹'],
    japanese_free_of_charge_button: ['🈚'],
    japanese_prohibited_button: ['🈲'],
    japanese_acceptable_button: ['🉑'],
    japanese_application_button: ['🈸'],
    japanese_passing_grade_button: ['🈴'],
    japanese_vacancy_button: ['🈳'],
    red_circle: ['🔴'],
    orange_circle: ['🟠'],
    yellow_circle: ['🟡'],
    green_circle: ['🟢'],
    blue_circle: ['🔵'],
    purple_circle: ['🟣'],
    brown_circle: ['🟤'],
    black_circle: ['⚫'],
    white_circle: ['⚪'],
    red_square: ['🟥'],
    orange_square: ['🟧'],
    yellow_square: ['🟨'],
    green_square: ['🟩'],
    blue_square: ['🟦'],
    purple_square: ['🟪'],
    brown_square: ['🟫'],
    black_large_square: ['⬛'],
    white_large_square: ['⬜'],
    black_medium_square: ['◼️'],
    white_medium_square: ['◻️'],
    black_medium_small_square: ['◾'],
    white_medium_small_square: ['◽'],
    black_small_square: ['▪️'],
    white_small_square: ['▫️'],
    large_orange_diamond: ['🔶'],
    large_blue_diamond: ['🔷'],
    small_orange_diamond: ['🔸'],
    small_blue_diamond: ['🔹'],
    red_triangle_pointed_up: ['🔺'],
    red_triangle_pointed_down: ['🔻'],
    diamond_with_a_dot: ['💠'],
    radio_button: ['🔘'],
    white_square_button: ['🔳'],
    black_square_button: ['🔲'],
    chequered_flag: ['🏁'],
    triangular_flag_on_post: ['🚩'],
    crossed_flags: ['🎌'],
    black_flag: ['🏴'],
    white_flag: ['🏳️'],
    rainbow_flag: ['🏳️‍🌈'],
    transgender_flag: ['🏳️‍⚧️'],
    pirate_flag: ['🏴‍☠️'],
    // Add more mappings as needed
};

const fallbackEmojis = ['🎲', '🤯', '❓', '🤔', '🤷', '🤦', '💔', '💥', '✨', '👽', '🤖', '👻'];

function getKeywordFromImage(img) {
    if (img.alt) {
        const altKeywords = img.alt.split(/[\s\-_.]+/);
        for (const keyword of altKeywords) {
            if (emojiMap[keyword]) return keyword;
        }
    }
    if (img.title) {
        const titleKeywords = img.title.split(/[\s\-_.]+/);
        for (const keyword of titleKeywords) {
            if (emojiMap[keyword]) return keyword;
        }
    }
    if (img.src) {
        const filename = img.src.split(/[\?]/)[0]; // Get the part before any query parameters
        const filenameKeywords = filename.split(/[\s\-_.]/);
        for (const keyword of filenameKeywords) {
            if (emojiMap[keyword]) return keyword;
        }
        // Check path segments
        const pathSegments = filename.split('/');
        for (let i = pathSegments.length - 2; i >= 0; i--) {
            const segment = pathSegments[i];
            if(emojiMap[segment]) return segment;
        }
    }
    return null;
}


function replaceImageWithEmoji(img, chaosMode = false) {
    if (img.classList.contains('emoji-fallback-processed')) {
        return; // Already processed
    }

    const keyword = getKeywordFromImage(img);
    let emoji;
    if (keyword && emojiMap[keyword]) {
        const emojis = emojiMap[keyword];
        if (Array.isArray(emojis) && emojis.length > 0) {
            emoji = emojis[Math.floor(Math.random() * emojis.length)];
        } else {
            emoji = emojis; // Fallback for single emoji strings
        }
    }
    
    if (!emoji) {
        emoji = fallbackEmojis[Math.floor(Math.random() * fallbackEmojis.length)];
    }

    const span = document.createElement('span');
    span.textContent = emoji;
    span.className = 'emoji-fallback';

    // Maintain aspect ratio and size
    const width = img.width || 100;
    const height = img.height || 100;

    // Style the fallback span
    span.style.width = `${width}px`;
    span.style.height = `${height}px`;
    span.style.display = 'inline-block';
    span.style['text-align'] = 'center';
    span.style['line-height'] = `${height}px`;
    span.style['font-size'] = `${Math.min(width, height)}px`;
    span.style['animation'] = 'fadeIn 0.5s';

    // Replace the image
    if (img.parentNode) {
        img.parentNode.replaceChild(span, img);
    }

    // Mark as processed
    span.classList.add('emoji-fallback-processed');
}

function handleAllImages(chaosMode) {
    const images = document.querySelectorAll('img');
    images.forEach(img => {
        if (chaosMode) {
            // In chaos mode, replace immediately if the image is already loaded,
            // or set an onload handler to replace it once it loads.
            // This ensures even working images are replaced.
            if (img.complete) {
                replaceImageWithEmoji(img, true);
            } else {
                img.onload = () => replaceImageWithEmoji(img, true);
                // Also handle errors in case it breaks while chaos mode is on
                img.onerror = () => replaceImageWithEmoji(img);
            }
        } else {
            // If not in chaos mode, only set the error handler.
            img.onerror = () => replaceImageWithEmoji(img);
        }
        // Add a class to prevent re-processing
        img.classList.add('emoji-fallback-processed');
    });
}


// Initial run
chrome.storage.sync.get('chaosMode', (data) => {
    handleAllImages(!!data.chaosMode);
});

// Listen for changes in chaos mode
chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
    if (request.chaosMode !== undefined) {
        // Re-evaluate all images when chaos mode changes
        // Reset processed flags to re-apply logic
        document.querySelectorAll('.emoji-fallback-processed').forEach(el => el.classList.remove('emoji-fallback-processed'));
        const images = document.querySelectorAll('img');
        images.forEach(img => {
            // If we are turning chaos mode on, we need to re-process all images.
            // If we are turning it off, we should ideally restore original images,
            // but for simplicity, we'll just stop replacing new ones. A page refresh would be needed to restore.
            // A more advanced implementation would store the original src and put the img back.
        });
        handleAllImages(request.chaosMode);
    }
});

// Use a MutationObserver to detect images added to the DOM later
const observer = new MutationObserver((mutations) => {
    mutations.forEach((mutation) => {
        mutation.addedNodes.forEach((node) => {
            if (node.tagName === 'IMG') {
                 chrome.storage.sync.get('chaosMode', (data) => {
                    handleAllImages(!!data.chaosMode);
                });
            }
            // Also check for images inside added nodes
            if (node.querySelectorAll) {
                const newImages = node.querySelectorAll('img');
                if (newImages.length > 0) {
                     chrome.storage.sync.get('chaosMode', (data) => {
                        handleAllImages(!!data.chaosMode);
                    });
                }
            }
        });
    });
});

observer.observe(document.body, {
    childList: true,
    subtree: true
});
